### PR TITLE
Auto api doc 2

### PR DESCRIPTION
**Pull request by stufisher**
Add missing packages

### CODE REVIEW

**Comment by stufisher** [comment]
Try again @clemenbor, as expected i broke the ci :(

**Review by clemenbor — APPROVED** [review]

**Comment by clemenbor** [comment]
Yep @stufisher , it's fine now :)

**Comment by stufisher** [comment]
Excellent! And heres the doc, i need to add a link from mkdocs: https://ispyb.github.io/py-ispyb/api/

**Comment by clemenbor** [comment]
@stufisher ok I'll do that

**Pull request merged**
