### PR TITLE
Fix SQLAlchemy model warnings

### PR DESCRIPTION
**Pull request by mgaonach**

### CODE REVIEW

**Comment by mgaonach** [comment]
- Regenerated models with last version of `sqlacodegen`;
- Specified what needs to be modified for it to be used;
- Documentation on generation procedure.

**Comment by stufisher** [comment]
I was thinking we might want to move the models out into their own package:

* they can be reused by other python projects
* we can generate the core `models.py` in CI automatically from https://github.com/ispyb/ispyb-docker-pydb
* generate a tagged release that matches the db version

it would also be good to try to avoid patching as much as possible by using the import/export pattern used here: https://github.com/DiamondLightSource/ispyb-api/blob/master/src/ispyb/sqlalchemy/__init__.py. 

Some things will still need to be patched, i.e. declarative base probably. 

What do you think?

**Comment by mgaonach** [comment]
Moving it to a separate package sounds like a good idea, but should be agreed with the collaboration first.
I think we could work with this to remove the warnings and discuss it in a framework working group meeting. 

I'm not sure to get this import pattern right. Does that mean you have to make the modifications every time you import it? And the patch I apply mainly removes problematic declarations, so you can't really do it like this I think.

**Comment by stufisher** [comment]
Yep, sounds good. I will raise it in the next framework meeting.

I was thinking you could maybe do something like:

rename `models.py` -> `_auto_models.py`
then:
`models.py`:
```
from _auto_models import *
from _auto_models import Image, AbInitioModel

...

Image.DataCollection1 = None

...

AbInitioModel.Model1 = None
AbInitioModel.ShapeDeterminationModel = relationship(
         "Model",
         primaryjoin="AbInitioModel.shapeDeterminationModelId == Model.modelId",
     )

```

Now you can import models normally. But you could be right, this may not work, i dont know if you can None a relationship that already exists.

This way we can always  generate the models file (without major editing) automatically, and apply any custom modifications in our local `models.py`

**Review by stufisher — APPROVED** [review]

**Comment by mgaonach** [comment]
@clemenbor sounds good to you?

**Review by clemenbor — APPROVED** [review]
Fine for me

**Pull request merged**
