### PR TITLE
152 add a folder for the minutes

### PR DESCRIPTION
**Pull request by antolinos**

### CODE REVIEW

**Review by mgaonach — APPROVED** [review]

**Comment by KarlLevik** [comment]
Would it not have been better to put these into a separate repository (but within the ispyb organisation)? Most of these meetings were unrelated to py-ispyb. Also, probably not optimal to have potentially large binary files in a code repo.

**Comment by antolinos** [comment]
Sure, I agree. In the last meeting, several possibilities to make them public were mentioned (repo, wiki, etc...). I think that any of these will work for me.

Personally, I'd use the same approach as MxCube. I think they have created a dedicated repo for that as you said:
https://github.com/mxcube/mxcube

I just wanted to address the urgent need of making the minutes public in a quick way. It enforces that everybody is aware of the minutes and presentations are produced and made available but I agree that it is not optimal.

Could a long term solution can be discussed in the documentation working group @rhfogh?

**Comment by stufisher** [comment]
The project is now 240mb to checkout! I dont know if this can be undone without rewriting the history?

**Comment by ndevenish** [comment]
No, not without rewriting the history

**Comment by stufisher** [comment]
Oh nice, thanks! I think maybe its best to remove all minutes and put them in a separate repo as @KarlLevik suggested, rather than having a subset? Some notes in the future could be large too (presentations with images, etc)?

**Comment by antolinos** [comment]
@rhfogh will check within the documentation working group what is the best but I agree that it is the easiest (and probably good enough).

As I have to do a `push`, please double check if this seems ok to you:
```
git clone --mirror https://github.com/ispyb/py-ispyb.git
java -jar ~/Downloads/bfg-1.14.0.jar --strip-blobs-bigger-than 1M py-ispyb.git
git reflog expire --expire=now --all && git gc --prune=now --aggressive
```

If it is ok for you, let me know and I will `git push`. First time I use `bfg`, if someone has a better/safer way to do it, you are welcome.

**Comment by rhfogh** [comment]
The minutes files are still available from the old repo, right? I am not really up with git commands, but as long as the data are available elsewhere, please do your worst ;-)

**Comment by antolinos** [comment]
> The minutes files are still available from the old repo, right?

I got a local copy of the /minutes that I can upload to the new repo

> please do your worst ;-)

I will wait for someone else to confirm, I will be happy to share the responsibility... :smile:

**Comment by mgaonach** [comment]
why not just remove the commit that added the minutes directory?

**Comment by stufisher** [comment]
Yes i think thats probably the easiest, remove the commit and rewrite the history. Its only a single commit afaik https://github.com/ispyb/py-ispyb/commit/37fe33a8b3fbf1d9702fe402c0baa48afa8662a5

**Comment by mgaonach** [comment]
I removed the commit from all the branches and forced pushed them. Now everyone needs to clone again or reset to origin, so that we don't get history conflicts. I'll send an email around to notify everyone.
The `master` branch is a protected branch, so it is not possible for someone to push the commit back by mistake.

**Pull request merged**
